<?php
namespace app\common\model;

class SceneQrcode extends \app\common\model\BaseModel
{
    public $platform_arr = [
        0=>'公众号二维码',
        1=>'触屏二维码',
        2=>'微信小程序码'
    ];
    public $type_arr = [
        'index'=>[
            'name'=>'首页',
            'alias'=>'index',
            'offiaccount_param_name'=>'',
            'mobile_page'=>''
        ],
        'reg_personal'=>[
            'name'=>'求职者注册页',
            'alias'=>'reg_personal',
            'offiaccount_param_name'=>'',
            'mobile_page'=>'member/reg/personal'
        ],
        'reg_company'=>[
            'name'=>'企业注册页',
            'alias'=>'reg_company',
            'offiaccount_param_name'=>'',
            'mobile_page'=>'member/reg/company'
        ],
        'company'=>[
            'name'=>'公司详情页',
            'alias'=>'company',
            'offiaccount_param_name'=>'comid',
            'mobile_page'=>'company/:id'
        ],
        'job'=>[
            'name'=>'职位详情页',
            'alias'=>'job',
            'offiaccount_param_name'=>'jobid',
            'mobile_page'=>'job/:id'
        ],
        'resume'=>[
            'name'=>'简历详情页',
            'alias'=>'resume',
            'offiaccount_param_name'=>'resumeid',
            'mobile_page'=>'resume/:id'
        ],
        'notice'=>[
            'name'=>'公告详情页',
            'alias'=>'notice',
            'offiaccount_param_name'=>'noticeid',
            'mobile_page'=>'notice/:id'
        ],
        'jobfairol'=>[
            'name'=>'网络招聘会详情页',
            'alias'=>'jobfairol',
            'offiaccount_param_name'=>'jobfairolid',
            'mobile_page'=>'jobfairol/:id'
        ]
    ];
}
